// Generated by `wrangler types` from config, bindings, and secrets.

export type Bindings = Env;

// extend the ContextVariableMap for services and vars manually added to the context
declare module "hono" {
	interface ContextVariableMap {}
}
