name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm' # Change to 'yarn' or 'pnpm' if needed

      - name: Install dependencies
        run: pnpm install # Change to 'yarn install' or 'pnpm install' if required

      - name: Build Project
        run: pnpm run build # Ensure your package.json has a "build" script

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist